apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: test-rabbitmq
spec:
  clusterIP: None
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
  - name: http-management-console
    port: 15672
    protocol: TCP
  selector:
    app: rabbitmq