apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rb-nodereader-rabbitmq-test-rabbitmq
  namespace: test-rabbitmq
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: test-rabbitmq
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: rb-endpointreader-rabbitmq-test-rabbitmq
  namespace: test-rabbitmq
subjects:
- kind: ServiceAccount
  name: rabbitmq
  namespace: test-rabbitmq
roleRef:
  kind: ClusterRole
  name: endpoint-reader
  apiGroup: rbac.authorization.k8s.io